### PR TITLE
Added example of reading input file for unoptimized config in 0D solver docs

### PR DESCRIPTION
**Pull request by alexkaiser**
It was unclear that the json must be opened then passed to the calibrator. Added instructions for reading that file accordingly. 

## Current situation
*Link any open issues or PRs related to this PR. Please ensure that all non-trivial PRs are first tracked and discussed in an existing GitHub issue or discussion.*

## Release Notes 
*Add a bullet point list summary of the feature and possible migration guides if this is a breaking change so this section can be added to the release notes.*

## Documentation
 
*Please ensure that you properly document any additions.*

## Testing
*Please ensure that the PR meets the testing requirements set by GitHub Actions.*
 
*In addition, please ensure all modified and new code is covered by tests.*

## Code of Conduct & Contributing Guidelines 
- [ ] I agree to follow the [Code of Conduct](https://github.com/SimVascular/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/SimVascular/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ktbolt** [comment]
@alexkaiser The `calibrate` function input argument is a Python object, does not need to be read in from a file. The `my_unoptimized_config = {...}` statement does demonstrate this but it is not very informative.

The `svZeroDCalibrator - Quick User Guide` should be reorganized to first describe what it does and what data it uses (config file). And after that show an example for Python and C++ how to use `calibrate`.

**Comment by ktbolt** [comment]
@alexkaiser And an Issue should have been opened for this.

**Comment by alexkaiser** [comment]
Okay, please feel free to discard the pull request and change otherwise, for minor changes will open an issue in the future.

**Comment by ktbolt** [comment]
@alexkaiser Thanks for bringing this problem to our attention!

I have opened an [Issue](https://github.com/SimVascular/simvascular.github.io/issues/37) for it.

**Pull request closed without merging**
